### PR TITLE
Using php-7.4 version instead

### PR DESCRIPTION
**Pull request by peter279k**
# Changed log
- The `php-7.4` is included on Travis CI build.

### CODE REVIEW

**Comment by peter279k** [comment]
The CI build service is failed because of following error message:

```
PHPUnit 7.1.5 by Sebastian Bergmann and contributors.
Runtime:       PHP 7.4.3 with Xdebug 2.9.2
Configuration: /home/travis/build/Lucky-Loek/Really-Simple-Http-Requests/phpunit.xml.dist
........E.                                                        10 / 10 (100%)
Time: 89 ms, Memory: 6.00MB
There was 1 error:
1) ReallySimpleHttpRequests\Test\RequestTest::itShouldCreateValidResponseOnSend
Function ReflectionType::__toString() is deprecated
/home/travis/build/Lucky-Loek/Really-Simple-Http-Requests/tests/RequestTest.php:104
ERRORS!
```

It seems that this issue is happened on PHPUnit version.

The possible solution is as follows:

- Defining different PHPUnit versions to be compatible with different PHP versions.
And it should updates the `composer.lock`.

**Comment by peter279k** [comment]
After my tests, it seems that the PHPUnit version should be upgraded to `^7.5`.

And this issue will be accomplished.

**Comment by Lucky-Loek** [comment]
I would even suggest to take out the lock file altogether. Feel free to do so!

**Comment by peter279k** [comment]
> I would even suggest to take out the lock file altogether. Feel free to do so!

Perhaps we can just upgrade the `composer.lock` to let cached dependencies can be compatible with all available PHP versions.

**Comment by peter279k** [comment]
I just upgrade the cached dependencies on `composer.lock` with `php-7.1` version.

And the CI build will be done :).

**Pull request merged**
